apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
   # this setting is t make sure the source IP address is preserved.
  externalTrafficPolicy: Local
  type: NodePort 
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
    nodePort: 32224
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
    nodePort: 32225
  selector:
    app: nginx-ingress  
